config/routes.rb
Rails.application.routes.draw do
  
    namespace :api do
      resources :books
      resources :authors
    end

  resources :books
  resources :authors

  root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors, dependent: :destroy	
end

app/controllers/api/authors_controller.rb
module API
  class AuthorsController < ApplicationController
    before_action :set_author, only: [:show, :edit, :update, :destroy]

    # GET /authors
    # GET /authors.json
    def index
      authors = Author.all
      render json: authors
    end

    # GET /authors/1
    # GET /authors/1.json
    def show
      render json: @author
    end



    # POST /authors
    # POST /authors.json
    def create
      author = Author.new(author_params)
      author.book_ids = params[:author][:book_ids]
      if author.save
        render json: author, status: :created, location: author
      else
        render json: author.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /authors/1
    # PATCH/PUT /authors/1.json
    def update
      if @author.update(author_params)
        @author.book_ids = params[:author][:book_ids]
        render json: @author
      else
        render json: @author.errors, status: :unprocessable_entity
      end
    end

    # DELETE /authors/1
    # DELETE /authors/1.json
    def destroy
      @author.destroy
      respond_to do |format|
        format.json { head :no_content, status: 200 }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_author
        @author = Author.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def author_params
        params.require(:author).permit(:name, book_ids: [])
      end
  end
end

app/controllers/api/books_controller.rb
module API
  class BooksController < ApplicationController
    before_action :set_book, only: [:show, :edit, :update, :destroy]

    # GET /books
    # GET /books.json
    def index
      books = Book.all
      render json: books
    end

    # GET /books/1
    # GET /books/1.json
    def show
      render json: @book
    end

    # POST /books
    # POST /books.json
    def create
      book = Book.new(book_params)
      if book.save
        book.author_ids = params[:author_ids]
        render json: book, status: :created, location: book
      else
        render json: book.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /books/1
    # PATCH/PUT /books/1.json
    def update
      respond_to do |format|
        if @book.update(book_params)
          @book.author_ids = params[:author_ids]
          format.json { render json: @book, status: :ok}
        else
          format.json { render json: @book.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /books/1
    # DELETE /books/1.json
    def destroy
      @book.destroy
      respond_to do |format|
        format.json { head :no_content, status: 200 }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_book
        @book = Book.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.  
      def book_params
        # byebug
        params.require(:book).permit(:name, :description,  author_ids: [])
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @books = @author.books
  end

  # GET /authors/new
  def new
    @author = Author.new
    @books = Book.all
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)
    @author.book_ids = params[:book_ids].reject(&:blank?)
    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        @author.book_ids = params[:book_ids].reject(&:blank?)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, {:book_ids => []})
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        @book.author_ids = params[:author_ids].reject(&:blank?)
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        @book.author_ids = params[:author_ids].reject(&:blank?)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :description, { author_ids:[] })
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= simple_form_for @author, :html => { :class => 'form-horizontal' } do |f| %>
<div class= 'fieldd'>
  <%= f.input :name%>
</div>
<b>Books</b>
  <%= collection_select(:book, :book_ids, Book.all, :id, :name,{:include_blank => 'None'},
{:multiple => true, :name=>'book_ids[]',:selected => 0,class: "form-control"}) %>
<br/>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                authors_path, :class => 'btn btn-default' %>
<% end %>

app/views/authors/edit.html.erb
<%- model_class = Author -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/authors/index.html.erb
<%- model_class = Author -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:books) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.id, author_path(author) %></td>
        <td><%= author.name %></td>
        <td><%= author.books.map{|c| c.name}.to_sentence %></td>
        <td><%=l author.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_author_path(author), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      author_path(author),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_author_path,
            :class => 'btn btn-primary' %>

app/views/authors/new.html.erb
<%- model_class = Author -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/authors/show.html.erb
<%- model_class = Author -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @author.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:books) %>:</strong></dt>
  <dd><%= @author.books.map{|s| s.name}.to_sentence %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              authors_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_author_path(@author), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              author_path(@author),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :class => 'form-horizontal' } do |f| %>
  <div class= 'fieldd'>
    <%= f.input :name %>
    <%= f.input :description %>
  </div>
  <b>Authors</b>
  <%= collection_select(:author, :author_ids, Author.all, :id, :name,{:include_blank => 'None'},
{:multiple => true, :name=>'author_ids[]',:selected => 0,class: "form-control"}) %>
<br/>
  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                books_path, :class => 'btn btn-default' %>
<% end %>

app/views/books/edit.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/index.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:authors) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.id, book_path(book) %></td>
        <td><%= book.name %></td>
        <td><%= book.description %></td>
        <td><%= book.authors.map{|c| c.name}.to_sentence %></td>
        <td><%=l book.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_book_path(book), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      book_path(book),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_book_path,
            :class => 'btn btn-primary' %>

app/views/books/new.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/books/show.html.erb
<%- model_class = Book -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @book.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @book.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:authors) %>:</strong></dt>
  <dd><%= @book.authors.map{|s| s.name}.to_sentence %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              books_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_book_path(@book), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              book_path(@book),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibraryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">

  <!-- <div class="navbar-inner"> -->

  	
    <div class="container menu">&emsp;&emsp;&emsp;&emsp;
         &emsp;&emsp;&emsp;&emsp;<%= link_to "Authors", authors_path %>&emsp;&emsp;&emsp;&emsp;
         &emsp;&emsp;<%= link_to "Books", books_path %>
        
    </div>
  <!-- </div> -->
</div>
<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>